# SPDX-FileCopyrightText: 2026 Shaan Narendran <shaannaren06@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only

name: 💡 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["accepted"]
body:
  - type: markdown
    attributes:
      value: |
        **Have a quick idea or want to gauge interest first?**
        Consider starting a conversation in our [GitHub Discussions](https://github.com/BlazeUp-AI/Observal/discussions) before filing a formal feature request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
